//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Djelatnik
    {
        public Djelatnik()
        {
            this.Prskanje = new HashSet<Prskanje>();
        }
    
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Lozinka { get; set; }
        public string BrojTelefona { get; set; }
        public Nullable<int> Admin { get; set; }
    
        public virtual ICollection<Prskanje> Prskanje { get; set; }
    }
}
