//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamjenaPovrsine
    {
        public NamjenaPovrsine()
        {
            this.polj_povrsina = new HashSet<PoljPovrsina>();
        }
    
        public int id { get; set; }
        public string namjena { get; set; }
    
        public virtual ICollection<PoljPovrsina> polj_povrsina { get; set; }
    }
}
