//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navodnjavanje
    {
        public int IdPovrsina { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<decimal> KolicinaVode { get; set; }
        public int IdStanja { get; set; }
        public int Id { get; set; }
    
        public virtual PoljPovrsina polj_povrsina { get; set; }
        public virtual StanjeNavodnjavanja StanjeNavodnjavanja { get; set; }
    }
}
