//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoljPovrsinaView
    {
        public int id { get; set; }
        public string naziv { get; set; }
        public decimal povrsina_m2 { get; set; }
        public string namjena { get; set; }
        public int id_namjena { get; set; }
        public decimal x_koordinata { get; set; }
        public decimal y_koordinata { get; set; }
    }
}
