//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SadniMaterijalView
    {
        public int id { get; set; }
        public string naziv { get; set; }
        public string jedinicna_mjera { get; set; }
        public string Vrsta { get; set; }
    }
}
