//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SadniMaterijal
    {
        public SadniMaterijal()
        {
            this.sadnja = new HashSet<Sadnja>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string jedinicna_mjera { get; set; }
        public int id_vrste_materijala { get; set; }
    
        public virtual VrstaSadnogMaterijala vrsta_sadnog_materijala { get; set; }
        public virtual ICollection<Sadnja> sadnja { get; set; }
    }
}
