//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class zastita
    {
        public zastita()
        {
            this.Prskanje = new HashSet<Prskanje>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string koncentracija { get; set; }
        public int id_vrste_zastite { get; set; }
    
        public virtual ICollection<Prskanje> Prskanje { get; set; }
        public virtual vrsta_zastite vrsta_zastite { get; set; }
    }
}
