//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prskanje
    {
        public int IdPovrsina { get; set; }
        public int IdZastita { get; set; }
        public System.DateTime Datum { get; set; }
        public string Opis { get; set; }
        public int IdDjelatnik { get; set; }
        public int Id { get; set; }
    
        public virtual Djelatnik Djelatnik { get; set; }
        public virtual polj_povrsina polj_povrsina { get; set; }
        public virtual zastita zastita { get; set; }
    }
}
