//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sadnja
    {
        public int id_povrsina { get; set; }
        public int id_materijal { get; set; }
        public System.DateTime datum_sadnje { get; set; }
        public string kolicina { get; set; }
        public int Id { get; set; }
    
        public virtual polj_povrsina polj_povrsina { get; set; }
        public virtual sadni_materijal sadni_materijal { get; set; }
    }
}
