//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrsta_sadnog_materijala
    {
        public vrsta_sadnog_materijala()
        {
            this.sadni_materijal = new HashSet<sadni_materijal>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<sadni_materijal> sadni_materijal { get; set; }
    }
}
