//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppVerzija2
{
    using System;
    using System.Collections.Generic;
    
    public partial class namjena_povrsine
    {
        public namjena_povrsine()
        {
            this.polj_povrsina = new HashSet<polj_povrsina>();
        }
    
        public int id { get; set; }
        public string namjena { get; set; }
    
        public virtual ICollection<polj_povrsina> polj_povrsina { get; set; }
    }
}
