//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppVerzija2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavodnjavanjeView
    {
        public System.DateTime Datum { get; set; }
        public string Povrsina { get; set; }
        public decimal PovrsinaM2 { get; set; }
        public string Naziv { get; set; }
        public Nullable<decimal> KolicinaVode { get; set; }
        public int Id { get; set; }
        public int IdPovrsina { get; set; }
        public int IdStanja { get; set; }
    }
}
