//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppVerzija2
{
    using System;
    using System.Collections.Generic;
    
    public partial class prskanje
    {
        public int id_povrsina { get; set; }
        public int id_zastita { get; set; }
        public System.DateTime datum { get; set; }
        public string opis { get; set; }
        public int id_djelatnik { get; set; }
    
        public virtual djelatnik djelatnik { get; set; }
        public virtual polj_povrsina polj_povrsina { get; set; }
        public virtual zastita zastita { get; set; }
    }
}
