//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppVerzija2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrskanjeView
    {
        public string Zastita { get; set; }
        public string Povrsina { get; set; }
        public System.DateTime Datum { get; set; }
        public string Opis { get; set; }
        public int IdZastita { get; set; }
        public int IdPovrsina { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int Id { get; set; }
    }
}
