//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppVerzija2
{
    using System;
    using System.Collections.Generic;
    
    public partial class prskanjeView
    {
        public string ime { get; set; }
        public string prezime { get; set; }
        public string naziv { get; set; }
        public string povrsina { get; set; }
        public System.DateTime datum { get; set; }
        public string opis { get; set; }
        public int id_zastita { get; set; }
        public int id_povrsina { get; set; }
    }
}
