//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppVerzija2
{
    using System;
    using System.Collections.Generic;
    
    public partial class sadni_materijal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sadni_materijal()
        {
            this.sadnja = new HashSet<sadnja>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string jedinicna_mjera { get; set; }
        public int id_vrste_materijala { get; set; }
    
        public virtual vrsta_sadnog_materijala vrsta_sadnog_materijala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sadnja> sadnja { get; set; }
    }
}
