//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoljoAppVerzija2
{
    using System;
    using System.Collections.Generic;
    
    public partial class stanje_navodnjavanja
    {
        public stanje_navodnjavanja()
        {
            this.navodnjavanje = new HashSet<navodnjavanje>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<navodnjavanje> navodnjavanje { get; set; }
    }
}
